<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <InvariantGlobalization>true</InvariantGlobalization>
        <UseSharedCompilation>false</UseSharedCompilation>
        <DefaultItemExcludes>$(DefaultItemExcludes);bin/**;obj/**;external/**;native/build/**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Raylib-cs" Version="7.0.2"/>
    </ItemGroup>

</Project>
