set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if (NOT DEFINED ROPTIX_LLVM_MINGW_ROOT)
    if (DEFINED ENV{ROPTIX_LLVM_MINGW_ROOT})
        set(ROPTIX_LLVM_MINGW_ROOT "$ENV{ROPTIX_LLVM_MINGW_ROOT}")
    else()
        message(FATAL_ERROR "ROPTIX_LLVM_MINGW_ROOT must point to the extracted llvm-mingw root.")
    endif()
endif()

set(ROPTIX_LLVM_MINGW_ROOT "${ROPTIX_LLVM_MINGW_ROOT}" CACHE PATH "Path to the extracted llvm-mingw root" FORCE)
set(ENV{ROPTIX_LLVM_MINGW_ROOT} "${ROPTIX_LLVM_MINGW_ROOT}")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ROPTIX_LLVM_MINGW_ROOT)

set(CMAKE_C_COMPILER "${ROPTIX_LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang")
set(CMAKE_CXX_COMPILER "${ROPTIX_LLVM_MINGW_ROOT}/bin/x86_64-w64-mingw32-clang++")
set(CMAKE_RC_COMPILER "${ROPTIX_LLVM_MINGW_ROOT}/bin/llvm-rc")

set(CMAKE_C_COMPILER_TARGET x86_64-w64-windows-gnu)
set(CMAKE_CXX_COMPILER_TARGET x86_64-w64-windows-gnu)

set(CMAKE_FIND_ROOT_PATH
    "${ROPTIX_LLVM_MINGW_ROOT}/x86_64-w64-mingw32"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
